apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vji538t04-python
  janus-idp.io/tekton: vji538t04-python
  backstage.io/kubernetes-id: vji538t04-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vji538t04-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
