apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vji538t04-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vji538t04-python 
  name: vji538t04-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vji538t04-python 
